from Listas import LinkedList

l = LinkedList()
print(f"¿L está vacía? {l.is_empty()}")
l.append(10)
l.append(5)
l.append(6)
l.append(20)
print(f"¿L está vacía? {l.is_empty()}")
l.transversal()
l.remove(10)
l.transversal()
print("-------------------")
l.preppend(3)
l.transversal()
x = l.tail()
print(x.data)
print(l.get())
print("¿Qué número se encuentra en la posición 2 de la lista l?")
print("El número en esa posicion es: " , l.get(2))
print("¿Qué número se encuentra en la posicion 1789 de la lista l")
print(l.get(1789))
